echo ""
echo ""
echo ""
echo ""
echo "  __      __       .__                                ___________                    __                                           "
echo " /  \    /  \ ____ |  |   ____  ____   _____   ____   \_   _____/__  __ ____   _____/  |______ ___  _______    ___________  ______"
echo " \   \/\/   // __ \|  | _/ ___\/  _ \ /     \_/ __ \   |    __)_\  \/ // __ \ /    \   __\__  \\  \/ /\__  \ _/ __ \_  __ \/  ___/"
echo "  \        /\  ___/|  |_\  \__(  <_> )  Y Y  \  ___/   |        \\   /\  ___/|   |  \  |  / __ \\   /  / __ \\  ___/|  | \/\___ \ "
echo "   \__/\  /  \___  >____/\___  >____/|__|_|  /\___  > /_______  / \_/  \___  >___|  /__| (____  /\_/  (____  /\___  >__|  /____  >"
echo "        \/       \/          \/            \/     \/          \/           \/     \/          \/           \/     \/           \/ "
echo ""
echo ""
echo "You're all set!"
echo "Drop the sites you generated server blocks for in your www folder within this vagrant project."
echo ""
echo "Some Vagrant commands:"
echo ""
echo "Command                           Description"
echo "vagrant up                        Start the virtual machine. This will reload any configuration changes you may have made."
echo "vagrant halt                      Shut down the virtual machine completely. This does not save state."
echo "vagrant suspend                   Suspend the virtual machine. This will save state."
echo "vagrant reload                    Reload vagrant configuration. The equivalent of doing vagrant halt followed by vagrant up."
echo "vagrant destroy                   This will delete your virtual machine. You can use vagrant up to bring it back"
echo "                                  but it will take a while to complete."
echo "Eat well and be merry."
echo "I HOLD ABSOLUTELY NOT RESPONSIBILITY FOR ANYTHING LOST OR STOLEN"
echo ""
echo ""
